// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMcoB4Bzrje2wQkAevW1EfCYcxvnRI-Ls',
    appId: '1:910982850712:web:b48620b524d37c1817c8ed',
    messagingSenderId: '910982850712',
    projectId: 'graduation-mental-chatbot',
    authDomain: 'graduation-mental-chatbot.firebaseapp.com',
    storageBucket: 'graduation-mental-chatbot.appspot.com',
    measurementId: 'G-5TXNYKFBBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIfig72blEDoWd2evisRUZjSrbd9JqZLg',
    appId: '1:910982850712:android:91935e4af4cb32db17c8ed',
    messagingSenderId: '910982850712',
    projectId: 'graduation-mental-chatbot',
    storageBucket: 'graduation-mental-chatbot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS0vPe7ar-ZEo6yy9upV25D_WJUFk1FQ0',
    appId: '1:910982850712:ios:439c3cc7e6b7dc0517c8ed',
    messagingSenderId: '910982850712',
    projectId: 'graduation-mental-chatbot',
    storageBucket: 'graduation-mental-chatbot.appspot.com',
    iosBundleId: 'com.example.mapfeatureProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS0vPe7ar-ZEo6yy9upV25D_WJUFk1FQ0',
    appId: '1:910982850712:ios:9c1c3c5305ec6d4517c8ed',
    messagingSenderId: '910982850712',
    projectId: 'graduation-mental-chatbot',
    storageBucket: 'graduation-mental-chatbot.appspot.com',
    iosBundleId: 'com.example.mapfeatureProject.RunnerTests',
  );
}
